# Generated by Django 3.1.4 on 2020-12-24 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='', max_length=255)),
                ('key', models.CharField(default='KEY', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('incoming', 'incoming'), ('outgoing', 'outgoing')], max_length=255)),
                ('from_number', models.CharField(max_length=255)),
                ('to_number', models.CharField(max_length=255)),
                ('is_send', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.users')),
            ],
        ),
    ]
